apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
data:
  appsettings.json: |-
    {
      .Files.Get "settings/appsettings.docker.json"
    }
#ref: https://www.mrjamiebowman.com/software-development/dotnet/kubernetes-configmaps-with-net-core/    