apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-microservies
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4 256k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/client-header-buffer-size: "64k"
    nginx.ingress.kubernetes.io/http2-max-field-size: "16k"
    nginx.ingress.kubernetes.io/http2-max-header-size: "128k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8 64k"    
spec:
  ingressClassName: nginx
  # tls:
  # - hosts:
  #     - myidentityserver.com
  #   secretName: identity-tls
  # - hosts:
  #     - booking-microservices.com
  #   secretName: booking-tls        
  rules:
    # - host: myidentityserver.com
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: identity-service
    #             port:
    #               number: 80
    - host: booking-microservices.com
      http:
        paths:
          - path: /flight
            pathType: Prefix
            backend:
              service:
                name: flight-service
                port:
                  number: 80
          - path: /passenger
            pathType: Prefix
            backend:
              service:
                name: passenger-service
                port:
                  number: 80
          - path: /booking
            pathType: Prefix
            backend:
              service:
                name: booking-service
                port:
                  number: 80                                                                